name: cron

on:
  push:
    branches:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '* * * * *'

jobs:
  provide-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: set-matrix
        run: echo "::set-output name=matrix::$(git tag -l)"
    outputs:
      matrix: ${{ toJson(steps.set-matrix.outputs.matrix) }}


  rebuild-tags:

    needs: provide-tags
  
    runs-on: ubuntu-latest

    # env:
    #   DOCKER_HUB_ACCOUNT: bmngld
    
    strategy:
      matrix:
        tag: ${{fromJson(needs.provide-tags.outputs.matrix)}}
    steps:
      # - uses: actions/checkout@v2

      - run: echo ${{ matrix.tag }}
      # - run: make ci
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # - run: docker tag test $DOCKER_HUB_ACCOUNT/${{ github.event.repository.name }}:${{ steps.vars.outputs.tag }}

      # - run:  echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username $DOCKER_HUB_ACCOUNT --password-stdin

      # - run: docker push $DOCKER_HUB_ACCOUNT/${{ github.event.repository.name }}:${{ steps.vars.outputs.tag }}
